[package]
name = "axum-sqlx-tx"
version = "0.1.0"
edition = "2021"

[features]
postgres = ["sqlx/postgres"]

[dependencies]
axum-core = "0.1.2"
futures = "0.3.21"
http = "0.2.6"
sqlx = { version = "0.5.11", default-features = false }
thiserror = "1.0.30"
tower-layer = "0.3.1"
tower-service = "0.3.1"

[dev-dependencies]
axum = "0.4.5"
sqlx = { version = "0.5.11", features = ["postgres", "runtime-tokio-rustls"] }
tokio = { version = "1.17.0", features = ["macros"] }
tower = "0.4.12"
